### ISSUE TITLE
Block glyphs on Browser

### ISSUE THREAD

**Issue by mmacedoeu** [qntm/base65536gen#1]
Amazing work you have done here, could you explain why is there so many Block 𠝷 glyphs when rendering on Browser (Chrome) ?

Ex.:

𠝷庨𣁵鏣墲𠱵𤧬䪁𢓻𧳻笅𒆴𡧔𥿁𥪻𠹇𓈾䈣扟𥃯𣕫𧓷儬𧡉奒㧡鈂铅𢄈𠦽𦬅𠜝𦀂𡗧𦎆栥𣔼囐𢗆𧈜狋讆𠂣𠙓𔑿𒂑瓈㐀㰄𦂦𣔡𦤨𧀄𤫈熷𦞪ꕍ鞾𨍢𢅨䠋𤏂勔𦢨𡦂籨𣉬𧂄輏𦉷𡮺𣅎𧦸𦬓䤍蘍鋘𧏃撯𓀅㙌簾䜱ꍑ䈡垾𥫹𖥧㢇𤒙䐗竧途㢌ꈩ㐀鈉笂𠏂㙀崁𨀱𡊷驅𥽗𥩁𡮼𢶳𦿝傎㦚𢌦𣐓𣺢𔕿沄𡟝尙𣼊荦䛡𧊣𡛩首𢮏𧬾𤈋𡔜𠇒𓇠砷𔕐𤗑陶桗棵𡇶蚒𢾸𢄎𠓼𢚩搛㐀𢏬𧄹𧞹𡰟𧘭𥠢䠿𧼱挅𠗰痜䬤𣐪𤊯𥦖㔎𢑅ꅆ𓃃沵𨃯罓𦙑𤂹𥟮ꗟ𦹧䚲霠𢅌迯𦾒抓劵爙𠝷𢟻䈵𦧉橞𐚮糶𢒔摟𧚇𣝕蟿㐀𠇡𥮥𒊄𠌓𦄿𠉏𧽬𡍎檠𥎑𣉖䭼𧶳𠋪闧𖤸𢆤𥶁猐𔑱𒊭𣘛𥀠𠶴𦞈𢜲𦤣迼漢𧈖㘻𤬋𣔾䜯䄜𧇞𦗺穏𦤚蹗𨑠繬𣌾𥎔𡽕𓏀聹㐀䔻𓏍𤀞𠊬𥑻𠻗𧟟𥬛渪ꍙ𢴏広㬸𤘡𣨖䧷骻ꎌ䦫𥇻𡧸𡓨秾𠀞𠛠脌𣧳㺤䘿𥥦𧯀餳噎𡤓圿𥺷魷枋𠀭𡀛苝𔓝𦐱𠆬𠲄ꇧ歒㐀𡩼𢧄𤜪𣅗忳𢔁廜戟𨊉𢂚𣌂華柷𡹊汳蔨鸱詍葺萔骽㝃伴𤔄罛諩㷟𦃿𥟙壿𢕶𤧭𠤸𦺇𠴶𥆙輱湺𧶭𤻕𢂉㔝𨊕𥋊䧷艇勌㐀𢃘𣭒𡦕𣕶封𣎻蔑𢷃𦀥𡻞ꎲ䍉疂譎𠮃怇㩰谀緁趶潟𢒿𤗃𓌼锰𦈽㢌𤍷𡢿𧉑𦩌𧜩𣥜𧘴𥮣𠁧𣮍𣿡𤋨佴𠆸𠮵庄𧦩㹋𠫯栔㐀

**Comment by qntm** [comment]
This is mainly a problem of font support. On my home computer almost all of those characters render correctly, but only about half on my phone. You can get closer to 100% by installing the correct fonts, maybe. Given another chance, I would focus harder on choosing characters with better support, but such is life.

**Comment by mmacedoeu** [comment]
I did a research on the number of glyphs per font and looks like https://en.wikipedia.org/wiki/Code2000 font has the widest coverage with 64k glyphs:

http://www.fontspace.com/james-kass/code2000/21107/charmap

I am no font specialist and don't really know how the font fallback mechanism kick in but without the knowledge I would reverse engineer the Unicode point codes from an existing font like code2000 or other with full range as only 64k glyphs are allowed per font and it match the range we are looking for in base64K
